macos_task:
  osx_instance:
    image: catalina-base
  environment:
    CIRRUS_KEY: ENCRYPTED[0d928cf2f2b4e912a319e684389a48e71ef890d05fea5287ab4b26adc25093395010d777f7ab56cefeb0458b9667cb5a]
  timeout_in: 10m
  script: |
    chmod +x cc-bootstrap
    cd unix-88
    ../cc-bootstrap
    cd ..
    mkdir -p Target/macOS
    cp graphviz Target/macOS
    cp ocat Target/macOS
    cp odc2txt Target/macOS
    cp oef Target/macOS
    cp ofront+ Target/macOS
    cp omake Target/macOS
    cp showdef Target/macOS
    mv Target/Linux_aarch64/Bin/.cirrus.yml .
    git add .cirrus.yml
    git add Target
    git -c user.name='zorko' -c user.email='zorko@vedasoft' commit -m "cc #macos"
    git push -q https://Oleg-N-Cher:$CIRRUS_KEY@github.com/Oleg-N-Cher/OfrontPlus-bootstrap.git HEAD:master &>/dev/null
