freebsd_task:
  freebsd_instance:
    image_family: freebsd-12-3
    cpu: 2
    memory: 2G
  container:
    image: gcc:latest
  environment:
    CIRRUS_KEY: ENCRYPTED[0d928cf2f2b4e912a319e684389a48e71ef890d05fea5287ab4b26adc25093395010d777f7ab56cefeb0458b9667cb5a]
  script: |
    chmod +x cc-bootstrap
    cd unix-88
    ../cc-bootstrap
    cd ..
    mkdir -p Target/FreeBSD_amd64
    cp graphviz Target/FreeBSD_amd64
    cp ocat Target/FreeBSD_amd64
    cp odc2txt Target/FreeBSD_amd64
    cp oef Target/FreeBSD_amd64
    cp ofront+ Target/FreeBSD_amd64
    cp omake Target/FreeBSD_amd64
    cp showdef Target/FreeBSD_amd64
    git pull -q https://Oleg-N-Cher:$CIRRUS_KEY@github.com/Oleg-N-Cher/OfrontPlus-bootstrap.git HEAD:master &>/dev/null
    test -f .cirrus.yml && git rm .cirrus.yml &>/dev/null
    git add Target
    git -c user.name='zorko' -c user.email='zorko@vedasoft' commit -m "cc #freebsd"
    git push -q https://Oleg-N-Cher:$CIRRUS_KEY@github.com/Oleg-N-Cher/OfrontPlus-bootstrap.git HEAD:master &>/dev/null
  on_failure:
    debug_script: |
      rm -r .git
      sleep 15
      git pull -q https://Oleg-N-Cher:$CIRRUS_KEY@github.com/Oleg-N-Cher/OfrontPlus-bootstrap.git HEAD:master &>/dev/null
      test -f .cirrus.yml && git rm .cirrus.yml &>/dev/null
      git add Target
      git -c user.name='zorko' -c user.email='zorko@vedasoft' commit -m "cc #$CIRRUS_OS"
      git push -q https://Oleg-N-Cher:$CIRRUS_KEY@github.com/Oleg-N-Cher/OfrontPlus-bootstrap.git HEAD:master &>/dev/null

linux_task:
  container:
    cpu: 2
    memory: 4G
    image: gcc:latest
  environment:
    CIRRUS_KEY: ENCRYPTED[0d928cf2f2b4e912a319e684389a48e71ef890d05fea5287ab4b26adc25093395010d777f7ab56cefeb0458b9667cb5a]
  script: |
    chmod +x cc-bootstrap
    cd unix-88
    ../cc-bootstrap
    cd ..
    mkdir -p Target/Linux_amd64
    cp graphviz Target/Linux_amd64
    cp ocat Target/Linux_amd64
    cp odc2txt Target/Linux_amd64
    cp oef Target/Linux_amd64
    cp ofront+ Target/Linux_amd64
    cp omake Target/Linux_amd64
    cp showdef Target/Linux_amd64
    git pull -q https://Oleg-N-Cher:$CIRRUS_KEY@github.com/Oleg-N-Cher/OfrontPlus-bootstrap.git HEAD:master &>/dev/null
    test -f .cirrus.yml && git rm .cirrus.yml &>/dev/null
    git add Target
    git -c user.name='zorko' -c user.email='zorko@vedasoft' commit -m "cc #$CIRRUS_OS"
    git push -q https://Oleg-N-Cher:$CIRRUS_KEY@github.com/Oleg-N-Cher/OfrontPlus-bootstrap.git HEAD:master &>/dev/null
  on_failure:
    debug_script: |
      rm -r .git
      sleep 15
      git pull -q https://Oleg-N-Cher:$CIRRUS_KEY@github.com/Oleg-N-Cher/OfrontPlus-bootstrap.git HEAD:master &>/dev/null
      test -f .cirrus.yml && git rm .cirrus.yml &>/dev/null
      git add Target
      git -c user.name='zorko' -c user.email='zorko@vedasoft' commit -m "cc #$CIRRUS_OS"
      git push -q https://Oleg-N-Cher:$CIRRUS_KEY@github.com/Oleg-N-Cher/OfrontPlus-bootstrap.git HEAD:master &>/dev/null

macos_task:
  osx_instance:
    image: catalina-base
  environment:
    CIRRUS_KEY: ENCRYPTED[0d928cf2f2b4e912a319e684389a48e71ef890d05fea5287ab4b26adc25093395010d777f7ab56cefeb0458b9667cb5a]
  script: |
    chmod +x cc-bootstrap
    cd unix-88
    ../cc-bootstrap
    cd ..
    mkdir -p Target/macOS
    cp graphviz Target/macOS
    cp ocat Target/macOS
    cp odc2txt Target/macOS
    cp oef Target/macOS
    cp ofront+ Target/macOS
    cp omake Target/macOS
    cp showdef Target/macOS
    git pull -q https://Oleg-N-Cher:$CIRRUS_KEY@github.com/Oleg-N-Cher/OfrontPlus-bootstrap.git HEAD:master &>/dev/null
    test -f .cirrus.yml && git rm .cirrus.yml &>/dev/null
    git add Target
    git -c user.name='zorko' -c user.email='zorko@vedasoft' commit -m "cc #macos"
    git push -q https://Oleg-N-Cher:$CIRRUS_KEY@github.com/Oleg-N-Cher/OfrontPlus-bootstrap.git HEAD:master &>/dev/null
  on_failure:
    debug_script: |
      rm -r .git
      sleep 15
      git pull -q https://Oleg-N-Cher:$CIRRUS_KEY@github.com/Oleg-N-Cher/OfrontPlus-bootstrap.git HEAD:master &>/dev/null
      test -f .cirrus.yml && git rm .cirrus.yml &>/dev/null
      git add Target
      git -c user.name='zorko' -c user.email='zorko@vedasoft' commit -m "cc #$CIRRUS_OS"
      git push -q https://Oleg-N-Cher:$CIRRUS_KEY@github.com/Oleg-N-Cher/OfrontPlus-bootstrap.git HEAD:master &>/dev/null
